### ISSUE TITLE
this engine has support for Symbol.toStringTag, but Float32Array does not have the property! Please report this

### ISSUE THREAD

**Issue by shentr** [inspect-js/which-typed-array#49]
Android 5.1.1 throw this error

**Comment by ljharb** [comment]
Thanks - what does `typeof Symbol.toStringTag` report?

**Comment by shentr** [comment]
typeof Symbol.toStringTag === 'symbol'  is true

**Comment by ljharb** [comment]
@shentr any idea which kind of android phones ship with v5.1.1? I only have browserstack available, and that only lists them by manufacturer.

Also, in which browser are you seeing this?

Also, what's the output of `var a = new Float32Array(); console.log([Symbol.toStringTag in a, a[Symbol.toStringTag], Object.getOwnPropertyDescriptor(a.__proto__.__proto__, Symbol.toStringTag).get])`?
